services:
  crappy-db:
    container_name: crappy-db
    image: postgres:latest
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=crappy
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./migrate/init.sql:/docker-entrypoint-initdb.d/init.sql
