name = "crappy_board"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.39.0 and < 2.0.0"
lustre = ">= 4.1.8 and < 5.0.0"
wisp = ">= 1.1.0 and < 2.0.0"
mist = ">= 2.0.0 and < 4.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
dot_env = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
gleam_pgo = ">= 0.10.0 and < 1.0.0"
beecrypt = ">= 0.3.1 and < 1.0.0"
valid = ">= 4.2.1 and < 5.0.0"
gleam_httpc = ">= 2.3.0 and < 3.0.0"
zeptomail = ">= 1.1.0 and < 2.0.0"
radish = ">= 0.15.0 and < 1.0.0"
minigen = ">= 0.1.1 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
glailglind = ">= 1.1.1 and < 2.0.0"

[tailwind]
version = "3.4.1" # optional
args = [
    "--config=tailwind.config.js",
    "--input=./src/css/app.css",
    "--output=./priv/static/app.css"
]
