name: Deploy Images to GHCR

# Only trigger, when the E2E Tests workflow succeeded
on:
  workflow_run:
    workflows: ["E2E Tests"]
    types:
      - completed

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/mrgleam/crappy-board:latest
          docker push ghcr.io/mrgleam/crappy-board:latest
