name: E2E Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres:latest

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: crappy_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Run migrations
      run: psql -f migrations/init.sql postgresql://postgres:postgres@localhost:5432/crappy_test
    - name: Run seeds
      run: |
        psql -f .github/workflows/seeds/users.sql postgresql://postgres:postgres@localhost:5432/crappy_test &&
        psql -f .github/workflows/seeds/boards.sql postgresql://postgres:postgres@localhost:5432/crappy_test
    - name: Set up Gleam, Beam
      uses: erlef/setup-beam@v1
      with:
        otp-version: "27.1.1"
        gleam-version: "1.5.1"
        rebar3-version: "3"
    - run: gleam deps download
    - run: gleam build
    - name: "Start Backend"
      env:
        BASE_URL: http://localhost:8000
        SECRET_KEY_BASE: test-secret-key
        EMAIL_API_KEY: ${{ secrets.EMAIL_API_KEY }}
        REDIS_HOST: localhost
        PG_USER: postgres
        PG_PASSWORD: postgres
        PG_HOST: localhost
        PG_PORT: 5432
        PG_DB: crappy_test
      run: |
        gleam run &
        sleep 30 &&
        curl http://localhost:8000 -I
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: e2e
      run: npm install -g yarn && yarn
    - name: Install Playwright Browsers
      working-directory: e2e
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      working-directory: e2e
      run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
    - name: Upload blob report to GitHub Actions Artifacts
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: blob-report-${{ matrix.shardIndex }}
        path: e2e/blob-report/
        retention-days: 1
  merge-reports:
    if: ${{ !cancelled() }}
    needs: [e2e_test]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      working-directory: e2e
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: e2e/all-blob-reports/
        pattern: blob-report-*
        merge-multiple: true

    - name: Merge into HTML Report
      working-directory: e2e
      run: npx playwright merge-reports --reporter html ./all-blob-reports

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: e2e/playwright-report/
        retention-days: 14