name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deploy Images to GHCR"]
    types:
      - completed

jobs:
  setup-and-preview:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Setup & Preview 
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: coursier/cache-action@v6

      - name: Set up Scala CLI (for Scala 3)
        uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: corretto:21

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5

      - name: Configure Pulumi
        run: pulumi login

      - name: Configure Pulumi Plugins
        run: pulumi plugin install language scala 0.3.2 --server github://api.github.com/VirtusLab/besom

      - name: Select Pulumi stack
        run: pulumi stack select planktonsoft/crappy-board-prod
  
      - name: Pulumi Preview
        run: pulumi preview