name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["E2E Tests"]
    types:
      - completed

jobs:
  setup-and-preview:
    name: Setup & Preview 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17 (for Scala 3)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Install the Eclipse Temurin distribution
          java-version: '17' # Scala 3 is compatible with Java 17

      - name: Cache sbt dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      - name: Add sbt repository and install sbt
        run: |
          echo "Adding sbt repository..."
          echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
          curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823" | sudo apt-key add -
          sudo apt-get update
          echo "Installing sbt..."
          sudo apt-get install sbt -y

      - name: Compile Scala code
        run: |
          echo "Compiling Scala code..."
          sbt clean compile

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5

      - name: Configure Pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi login