name: Deploy

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["E2E Tests"]
    types:
      - completed

jobs:
  setup-and-preview:
    name: Setup & Preview 
    env:
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      PULUMI_BACKEND_URL: ${{ secrets.PULUMI_BACKEND_URL }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: coursier/cache-action@v6

      - name: Set up Scala CLI (for Scala 3)
        uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: corretto:21

      - name: Pulumi Preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: planktonsoft/crappy-board-prod
          work-dir: infra